version: "3.8"

services:
  retool:
    image: tryretool/backend:latest
    container_name: retool
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      # Retool needs a Postgres metadata DB
      - RETOOL_DB_URL=postgres://retool:password@retool_postgres:5432/retool
      - TINI_SUBREAPER=true
    depends_on:
      - postgres

    volumes:
      # Mount your Mendrop CN H&H Report Tool app JSON into /retool/apps
      - "C:/Users/thoma/OneDrive/Documents/GitHub/MendropEngineering/Mendrop CN H&H Report Tool:/retool/apps"

  postgres:
    image: postgres
    container_name: retool_postgres
    restart: always
    environment:
      POSTGRES_USER: tboverton@gmail.com
      POSTGRES_PASSWORD: M@v3r!ck1
      POSTGRES_DB: retool
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


